../../bin/3way: 3way.c
	gcc 3way.c -g -I/inside/home/dzerbino/utils/sonLib/lib/ -I/inside/home/dzerbino/utils/pinchesAndCacti/externalTools/threeEdgeConnected/inc/ /inside/home/dzerbino/utils/sonLib/lib/sonLib.a /inside/home/dzerbino/utils/sonLib/lib/3EdgeConnected.a -o 3way
	mv 3way ../../bin
