../../bin/3way: 3way.c
	gcc 3way.c -g -I/Users/cbseuser/utils/sonLib/lib/ -I/Users/cbseuser/utils/cactus/externalTools/threeEdgeConnected/inc/ /Users/cbseuser/utils/sonLib/lib/sonLib.a /Users/cbseuser/utils/cactus/lib/3EdgeConnected.a -o 3way
	mv 3way ../../bin
