default: ../bin/3way ../bin/cbs ../bin/cn-avg.py ../bin/cn-avg-stats.py ../bin/braneyConversion.py ../bin/cn-avg-testor.py

../bin/cn-avg.py: cn-avg.py
	cp cn-avg.py ../bin

../bin/cn-avg-testor.py: cn-avg-testor.py
	cp cn-avg-testor.py ../bin

../bin/cn-avg-stats.py: cn-avg-stats.py
	cp cn-avg-stats.py ../bin

../bin/braneyConversion.py: braneyConversion.py
	cp braneyConversion.py ../bin

../bin/3way:
	cd 3way && make

../bin/cbs:
	cd cbs && make
